common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from sfoj_system import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sfoj_system/',  include('sfoj_system.urls')), #sfoj_system의 urls에서 urls를 관리 가능
    path('common/', include('common.urls')),
    path('', views.index, name='index'),  # '/' 에 해당되는 path
]

sfoj_system/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'sfoj_system'
"""
urls.py Ground rule
1. url path는 rendering 함수의 이름을 활용한다. 
2. 기본적으로 모두 소문자로 통일한다.
"""
urlpatterns = [
    path('', views.index, name='index'), #config의 'sfoj_system/'이 추가된 후 이곳의 url이 추가됨
    path('login/', auth_views.LoginView.as_view(template_name='common:login'), name='login'),
    path('list/',views.list, name = 'list'),
    path('list/<int:board_index>/', views.detail, name = 'detail'),
    path('uploads/',views.uploads, name='uploads'),
    path('signup/',views.signup, name='signup'),
]

common/models.py
from django.db import models

# Create your models here.

sfoj_system/models.py
from django.contrib.auth.models import User
from django.db import models
"""
models.py Ground rule
1. 모델명은 각 단어의 첫문자를 대문자로 설정한다
2. 각 모델의 속성은 소문자와 언더바를 활용한다
"""

class Board(models.Model):
    index = models.AutoField(primary_key=True)
    user_id = models.ForeignKey(User,on_delete=models.CASCADE) #uploads 렌더링함수에서 사용
    title = models.CharField(max_length=100)
    content = models.TextField()
    hit = models.IntegerField(default=0)
    #Success_per = models.IntegerField(null=True)
    reg_date = models.DateTimeField(null=True)


class Judge_State(models.Model):
    submit_idx = models.IntegerField()
    UserID = models.CharField(max_length=15)
    States = models.CharField(max_length=5) #perhaps true false?
    Memory_use = models.IntegerField()
    Time_Complex = models.IntegerField()
    Submission_Time = models.DateTimeField()

class Users(models.Model):
    username = models.CharField(max_length=32)
    password = models.CharField(max_length=64)
    useremail = models.CharField(max_length=128)
    reg_date = models.DateTimeField(auto_now_add = True)

class Code_History(models.Model):
    index = models.AutoField(primary_key=True)
    UserID = models.CharField(max_length=15)
    Board_idx = models.IntegerField()
    answer = models.TextField()

common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "email")

sfoj_system/forms.py
from django import forms
from sfoj_system.models import Board
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

# form 이란 model 처럼 속성들을 저장할 수 있는 틀.
# form 을 사용하는 이유는 parameter 가 유효하게 전달됐는지 등을 확인하기 위함.

class BoardForm(forms.ModelForm):
    class Meta:
        model = Board  # 사용할 모델
        fields = ['title','content']  # BoardForm에서 사용할 Board 모델의 속성

        labels = {
            'title' : '제목',
            'content' : '내용',
        }

class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ("username", "password1", "password2", "email")

common/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate, login
from django.shortcuts import render, redirect
from common.forms import UserForm


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})

sfoj_system/views.py
from django.db.models.fields import NullBooleanField
from django.http.response import HttpResponseBase
from django.shortcuts import get_object_or_404, render, redirect
from django.contrib.auth import authenticate, login
from django.db.models import Q
from django.http import HttpResponse
from .forms import BoardForm,UserForm
from .models import *
from django.utils import timezone
from django.core.paginator import Paginator
from django.contrib import messages

"""
views.py Ground rule
1. rendering 함수는 모두 소문자로 설정한다.
2. 각 함수에서 생성하는 객체의 리스트는 객체_list 라고 명명한다
3. 렌더링함수에 설명이 필요한 부분은 주석처리를 한다.
"""

# main
def index(request):
    return render(request, 'sfoj_system/index.html')

# 문제 리스트 조회
def list(request):
    # parameter
    page = request.GET.get('page', '1')  # 페이지
    kw = request.GET.get('kw','') # 검색어(keyword)
    so = request.GET.get('so','recent') # 정렬기준(sorting option), default = recent
    type = request.GET.get('search_type','all')


    # 정렬
    if so == 'old': # 오래된순
        board_list = Board.objects.order_by('reg_date')
    else: # 최신순
        board_list = Board.objects.order_by('-reg_date')

    # 검색
    if kw:
        if len(kw) > 1:
            if type == 'all': # 전체
                board_list = board_list.filter( Q(title__icontains=kw)|Q(content__icontains=kw)|Q(user_id__username__icontains=kw)).distinct()
            elif type == 'title': # 제목
                board_list = board_list.filter( Q(title__icontains=kw) ).distinct()
            elif type == 'title_content': # 제목+내용
                board_list = board_list.filter( Q(title__icontains=kw)|Q(content__icontains=kw) ).distinct()
            elif type == 'content': # 내용
                board_list = board_list.filter( Q(content__icontains=kw)).distinct()
            elif type == 'writer':  # 글쓴이
                board_list = board_list.filter( Q(user_id__username__icontains=kw) ).distinct()

        else: # error
            messages.error(request,'검색어는 2글자 이상 입력해주세요.')

    # 페이징 처리
    paginator = Paginator(board_list, 15)  # 한 페이지에 15개씩
    page_obj = paginator.get_page(page)

    context = {'board_list': page_obj,'page':page,'kw': kw, 'so':so, 'search_type': type }
    return render(request, 'sfoj_system/Board_list.html', context)

# 문제 상세
def detail(request, board_index):
    board = get_object_or_404(Board, pk=board_index)
    context = {'board': board}
    return render(request, 'sfoj_system/Board_detail.html', context)

# 문제 업로드
def uploads(request):
    # post ==> uploads화면에서 저장하기 버튼을 눌렀을 때
    # get ==> list화면에서 문제 업로드 버튼을 눌렀을때
    if request.method == 'POST':
        form = BoardForm(request.POST)
        if form.is_valid():
            board = form.save(commit=False)
            board.user_id = request.user #request에서 로그인한 user를 가져옴
            board.Reg_date = timezone.now()
            board.save()
            return redirect('sfoj_system:list')
    else:
        form = BoardForm()
    context = {'form':form}
    return render(request,'sfoj_system/Board_uploads.html',context)

# 회원가입
def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)  # 사용자 인증
            login(request, user)  # 로그인
            return redirect('sfoj_system:index')
    else:
        form = UserForm()
    return render(request, 'common:signup', {'form': form})

Judger/test_page/templates/form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Online Judge</title>
    <script
  src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
  integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs="
  crossorigin="anonymous"></script>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/vs2015.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.12.0/highlight.min.js"></script>
  <script>hljs.initHighlightingOnLoad();</script>

    <link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">
    <script src="{{ url_for('static', filename='index.js') }}"></script>

<style type="text/css">
    .page{
        overflow: auto;
    }
    .section1{
        margin: 20px;
        height: 400px;
        width: 800px;
        border: 3px solid #000000;
    }
    .code-box {
      float: left;
      width:300px;
      margin:20px;
    }
    .code-box textarea {
      width:300px;
      height:200px;
    }
    .highlight-box {
      float: right;
      width:400px;
      height:400px;
      margin:20px;
    }
    
    
</style>
</head>
<body onload="load()">
    <div id="container" class="page">
        <h1 style="margin-left: 20px;">
             Submit Testing
        </h1>
        <div style="margin: 20px;">
            Write a program that takes two numbers and prints their sum.
        </div>
        <div class="section1">
            <form class="code-box" action="{{ url_for('submit') }}" method="post">
                <p>
                    <input type="radio" id="LANG_C" name="LANG" value="C" required>
                    <label for="LANG_C">C</label>
                </p>
                <p>
                    <input type="radio" id="LANG_CXX" name="LANG" value="CXX" required>
                    <label for="LANG_CXX">CXX</label>
                </p>
                <textarea  name="source_code"></textarea>
                <input type="hidden" value="1000" name="problem_id">
                <input type="submit" value="submit">
            </form>
        
            {% if submit %}
            <div class="highlight-box">Code : <pre><code style="width:300px;height:300px" class="{{ code_language }}">{{ code }}</code></pre></div>
        </div>

        <div style="margin: 20px">
            <table>
                <thead><tr>Result :</tr></thead>
                <tbody>
                 {% for key, value in result.items() %}
                 <tr>
                    {% if value=="ACCEPTED" %}
                        <td>TestCase{{ key }} :<span style="color:green"> {{ value }}</span></td>
                    {% else %}
                        <td>TestCase{{ key }} :<span style="color:red"> {{ value }}</span></td>
                    {% endif %}
                </tr>
                 {% endfor %}
                 </tbody>
            </table>
        </div>
        {% endif %}
    
        
    </div>
</body>
</html>

templates/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Welcome to SFOJ</title>
        <link rel="icon" type="image/x-icon" href="{% static 'assets/img/favicon.ico' %}" />
        <link rel="preconnect" href="https://fonts.gstatic.com">
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.3/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Saira+Extra+Condensed:500,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Muli:400,400i,800,800i" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css2?family=Courgette&display=swap" rel="stylesheet">
        <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+KR:wght@400;500&display=swap" rel="stylesheet">
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet" />
    </head>
<body>
    {% include "navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
    <br>
    <br>
    <hr>
    {% include "footer.html" %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- jQuery JS -->
        <script src="{% static 'jquery-3.6.0.min.js' %}"></script>
        <!-- Bootstrap JS -->
        <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- 자바스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바스크립트 End -->
</body>
</html>

templates/common/login.html
{% extends "base.html" %}
{% block content %}
<!-- 상단 꾸미기 -->
<!Doctype html>
<div class="blue_sec">
    <div class="container">
        <div style="font-size:4rem;">
            <div class="top_info_lead">Login</div>
        </div>
    <div class="row">
        <div class="col-8 text-right">
            <span class="top_info_sub">아직 회원이 아니신가요? <a class="login_signup" style="font-weight:bold" href="{% url 'common:signup' %}">계정을 생성하세요.</a></span>
        </div>
    </div>
    </div>
</div>

<!-- 로그인 박스 -->
<div class="white_sec">
<div class="container">
    <div class="login_box">
    <form method="post" action="{% url 'common:login' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="textbox">
            <label for="username">아이디</label>
            <input type="text" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
            <label for="password">비밀번호</label>
            <input type="password" name="password" id="password"
                   value="{{ form.password.value|default_if_none:'' }}">
        </div>

        <button type="submit" class="login_btn">로그인</button>
    </form>
        <br>
        <div class="sign_and_find">
        <a href="{% url 'common:signup' %}">회원가입</a>
            <span>|</span>
        <a href="#find_id">아이디찾기</a>
            <span>|</span>
        <a href="#find_pw">비밀번호찾기</a>
        </div>
    </div>
</div>
</div>

{% endblock %}

templates/common/signup.html
{% extends "base.html" %}
{% block content %}
<!-- 상단 꾸미기 -->
<!Doctype html>
<div class="blue_sec">
    <div class="container">
        <div style="font-size:4rem;">
            <div class="top_info_lead">Sign up</div>
        </div>
    <div>
        <div>
            <span class="top_info_sub">이미 회원이신가요? <a class="signup_lgn" style="font-weight:bold" href="{% url 'common:login' %}">로그인</a></span>
        </div>
    </div>
    </div>
</div>

<!-- 회원가입 박스 -->
<div class="white_sec">
<div class="container">
    <div class="signup_box">
    <form method="post" action="{% url 'common:signup' %}">
        {% csrf_token %}
        {% include "form_errors.html" %}
        <div class="textbox">
            <label for="username">아이디</label>
            <input type="text" name="username" id="username"
                   value="{{ form.username.value|default_if_none:'' }}">
            <label for="password1">비밀번호</label>
            <input type="password" name="password1" id="password1"
                   value="{{ form.password.value|default_if_none:'' }}">
            <label for="password1">비밀번호 확인</label>
            <input type="password" name="password2" id="password2"
                   value="{{ form.password.value|default_if_none:'' }}">

            <label for="email">이메일</label>
            <input type="text" name="email" id="email"
                   value="{{ form.email.value|default_if_none:'' }}">
        </div>

        <button type="submit" class="signup_btn">가입하기</button>
    </form>
        <br>
        <div class="sign_and_find">
        <a href="{% url 'common:login' %}">로그인</a>
            <span>|</span>
        <a href="#find_id">아이디찾기</a>
            <span>|</span>
        <a href="#find_pw">비밀번호찾기</a>
        </div>
    </div>
</div>
</div>
{% endblock %}

templates/footer.html
{% load static %}
<!-- footer -->
<div style="text-align:center; margin-top:2rem;">
    <div style="font-size:18px;">

        <span>공지사항</span> |
        <span>제휴문의</span> |
        <span>서비스 소개</span>
    </div>
    <div style="margin-top:1rem;">
      <h3>sfoj</h3>
    </div>
</div>

templates/form_errors.html
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}  <!-- 필드 오류를 출력한다. -->
            <div class="alert alert-danger">
                <strong>{{ field.label }}</strong>
                {{ error }}
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}   <!-- 넌필드 오류를 출력한다. -->
        <div class="alert alert-danger">
            <strong>{{ error }}</strong>
        </div>
    {% endfor %}
{% endif %}

templates/navbar.html
{% load static %}
<!-- Navigation-->
    <nav class="navbar">
        <div class="navbar_logo">
            {% load static %}
            <a href="/"><img style="width:300px;height:150px;"src="{% static 'assets/img/sfoj_logo.jpg' %}"></a>
        </div>
        <ul class="navbar_menu">
            <li>
                <a class="navbar_menu" href="{% url 'sfoj_system:index' %}">home</a>
                <a class="navbar_menu" href="https://sites.google.com/d/1FmwHjb7_15XeQMd3oYBnXJvYB9_HtsCU/p/1MujXOH0Oi-tMGNoON-CtXv76fAxJHLHV/edit">about</a>
                <a class="navbar_menu" href="{% url 'common:signup' %}">sign up</a>
                <!-- 로그인 세션 활용 -->
                {% if user.is_authenticated %}
                <span class="navbar_menu_lgnout" style="font-weight:bold">({{ user.username }})님</span> <a class="navbar_menu_lgnout" href="{%url 'common:logout' %}">logout</a>
                {% else %}
                <a class="navbar_menu" href="{%url 'common:login' %}">login</a>
                {% endif %}
            </li>
        </ul>
        <a href="#" class="navbar_toggle">
            <i></i>
        </a>
    </nav>

templates/sfoj_system/Board_detail.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
<div class="container my-3">
    <h2 class="border-bottom py-2">{{ board.title }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ board.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge badge-light p-2">
                    {{ board.reg_date }}
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/sfoj_system/Board_list.html
{% extends 'base.html' %}
{% load sfoj_filter %}
{% block content %}
{% load static %}
<!-- 상단 꾸미기 -->
<div class="blue_sec">
    <div class="container">
        <div style="font-size:4rem;">
        <div class="top_info_lead">DO YOUR BEST<br>
        <span class="top_info_lead">Solve the problems</span>
    </div>
    </div>
</div>
</div>
<!-- page content -->
<div class="board_list_my_box"> <!-- 가장 큰 박스 -->
    <div style="padding:2.5rem 2.5rem 0 2.5rem">
        <div class="board_list_my_box_title">
        <div></div>
            <div class="board_list_title" >문제 목록</div>
                    <div>
                        <button class="bg_btn_style" style="margin-left:54rem;" onclick="location.href='{%url 'sfoj_system:uploads' %}'">문제 업로드</button>
                    </div>
                </div>
                <hr>
      <!-- 정렬 option start -->
         <div class="my-3 board_list_so_group">
            <select class="board_list_so_option so">
                <option value="recent" {% if so == 'recent' %}selected{% endif %}>최신순</option>
                <option value="recommend" {% if so == 'recommend' %}selected{% endif %}>추천순</option>
                <option value="popular" {% if so == 'popular' %}selected{% endif %}>인기순</option>
            </select>
             <button id="btn_so" class="board_list_so_btn" type="button"><img src="{% static 'assets/img/button_search.png' %}"></button>
        </div>
      <!-- 정렬 option end -->

    <table id="short_table" class="board_list_table" style="margin-top:2rem;">
        <thead>
        <tr>
            <th class="board_list_table_th" style="width:7%">번호</th>
            <th class="board_list_table_th" style="width:50%">문제제목</th>
            <th class="board_list_table_th" style="width:23%">작성일시</th>
            <th class="board_list_table_th" style="width:20%">작성자</th>
        </tr>
        </thead>
        <tbody class="index">
        {% if board_list %}
        {% for board in board_list %}
        <tr>
            <td class="board_list_table_td">
                <!-- 번호 = 전체건수 - 시작인덱스 - 현재인덱스 + 1 -->
                <!-- board_list.paginator.count : 전체건수
                     board_list.start_index : 시작 인덱스
                     forloop.counter0 : 현재 인덱스 -->
                {{ board_list.paginator.count|sub:board_list.start_index|sub:forloop.counter0|add:1 }}
            </td>
            <!-- /제목/작성일자/작성자  -->
            <td class="board_list_table_td">
                <a href="{% url 'sfoj_system:detail' board.index %}">{{ board.title }}</a>
            </td>
            <td class="board_list_table_td">{{ board.reg_date }}</td>
            <td class="board_list_table_td">{{ board.user_id }}</td>
        </tr>
        {% endfor %}
        {% else %}
        <tr>
            <td colspan="3">질문이 없습니다.</td>
        </tr>
        {% endif %}
        </tbody>
    </table>


        <!-- keywords search start -->
        <div class="justify-content-end1 my-3" style="margin-left:30rem">
        <div class="my-col board_list_search_group">
              <!-- 검색 option start -->
            <select class="board_list_search_option search_type" style="width:20%">
                <option value="all" {% if search_type == 'all' %}selected{% endif %}>전체</option>
                <option value="title_content" {% if search_type == 'title_content' %}selected{% endif %}>문제+제목</option>
                <option value="title" {% if search_type == 'title' %}selected{% endif %}>제목</option>
                <option value="content" {% if search_type == 'content' %}selected{% endif %}>내용</option>
                <option value="writer" {% if search_type == 'writer' %}selected{% endif %}>작성자</option>
            </select>
             <!-- 검색 option end -->
            <input type="text" class="kw" style="width:40%" value="{{ kw|default_if_none:'' }}">
            <button id="btn_search" style="width:25%" class="board_list_search_btn" type="button">검색</button>
        </div>
        </div>
      <!-- keywords search end -->

        <!-- 페이징처리 시작 -->
    <ul class="pagination justify-content-center">
        <!-- 이전페이지 -->
        {% if board_list.has_previous %}
        <li class="page-item">
            <a class="my_page_link" data-page="{{ board_list.previous_page_number }}" href="#">이전</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="my_page_link" tabindex="-1" aria-disabled="true" href="#">이전</a>
        </li>
        {% endif %}
        <!-- 페이지리스트 -->
        {% for page_number in board_list.paginator.page_range %}
            {% if page_number == board_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="my_page_link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="my_page_link" data-page="{{ page_number }}" href="#">{{ page_number }}</a>
            </li>
            {% endif %}
        {% endfor %}
        <!-- 다음페이지 -->
        {% if board_list.has_next %}
        <li class="page-item">
            <a class="my_page_link" data-page="{{ board_list.next_page_number }}" href="#">다음</a>
        </li>
        {% else %}
        <li class="page-item disabled">
            <a class="my_page_link" tabindex="-1" aria-disabled="true" href="#">다음</a>
        </li>
        {% endif %}
    </ul>
    <!-- 페이징처리 끝 -->



</div>
</div>
<form id="searchForm" method="get" action="{%url 'sfoj_system:list' %}">
    <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
    <input type="hidden" id="page" name="page" value="{{ page }}">
    <input type="hidden" id="so" name="so" value="{{ so }}"> <!-- so = search option -->
    <input type="hidden" id="search_type" name="search_type" value="{{ search_type }}">
</form>
{% endblock %}
{% block script %}
<script type='text/javascript'>
$(document).ready(function(){
    $(".my_page_link").on('click', function() {
        $("#page").val($(this).data("page"));
        $("#searchForm").submit();
    });

    $("#btn_search").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#so").val($(".so").val());
        $("#search_type").val($(".search_type").val());
        $("#page").val(1);
        $("#searchForm").submit();
    });

    $("#btn_so").on('click', function() {
        $("#kw").val($(".kw").val());
        $("#so").val($(".so").val());
        $("#search_type").val("all");
        $("#page").val(1);
        $("#searchForm").submit();
    });
});
</script>
{% endblock %}

templates/sfoj_system/Board_uploads.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
<!-- 상단 꾸미기 -->
<div class="blue_sec">
    <div class="container">
        <div style="font-size:4rem;">
        <div class="top_info_lead">SECURITY FACTORIAL<br>
        <span class="top_info_lead">Online Judge System</span>
    </div>
    </div>
</div>
</div>
<!-- page content -->
<div class="white_sec">
    <div class="container" class="board_uploads_my_box_title">
<div class="board_uploads_title">문제등록</div><br>
        <div class="board_uploads_sub">양식에 맞게 작성하여 자신의 문제를 등록하세요. </div>
        </div>
</div>

<!-- 문제 등록 박스 -->
<div class="board_uploads_my_box">
              <div class="board_uploads_container">
    <form method="post" class="">
        {% csrf_token %}
        <!-- 오류표시 Start -->
        {% if form.errors %}
            <div class="alert alert-danger" role="alert">
            {% for field in form %}
                {% if field.errors %}
                <strong>{{ field.label }}</strong>
                {{ field.errors }}
                {% endif %}
            {% endfor %}
            </div>
        {% endif %}
        <!-- 오류표시 End -->

        <div>
            <label class="board_uploads_sub" style="font-weight:bold" for="title">제목</label>
            <input type="text" class="board_uploads_form-control"  name="title" id="title"
                   value="{{ form.title.value|default_if_none:'' }}">
        </div>

        <div>
            <label class="board_uploads_sub" style="font-weight:bold" for="content">내용</label>
            <textarea class="board_uploads_form-control" name="content"
                      id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>

        <button type="submit" class="bg_btn_style">저장하기</button>
        </form>
</div>
</div>
<br>
<br>
<br>

{% endblock %}

templates/sfoj_system/index.html
{% extends 'base.html' %}
{% block content %}
{% load static %}
    <!-- 상단 꾸미기 -->
    <div class="blue_sec">
        <div class="container">
            <div style="font-size:4rem;">
            <div class="top_info_lead">SECURITY FACTORIAL<br>
            <span class="top_info_lead">Online Judge System</span>
            </div>
            </div>
        </div>
    </div>
    <!-- 상단 꾸미기 -->
    <div class="main1_sec">
        <div class="container">
            <div style="font-size:4rem;">
            <div class="top_info_lead">SECURITY FACTORIAL<br>
            <span class="top_info_lead">Online Judge System</span>
            </div>
            </div>
        </div>
    </div>
<!-- 상단 꾸미기 -->
    <div class="main2_sec">
        <div class="container">
            <div style="font-size:4rem;">
            <div class="top_info_lead">SECURITY FACTORIAL<br>
            <span class="top_info_lead">Online Judge System</span>
            </div>
            </div>
        </div>
    </div>
    <!-- Page Content-->
     <div class="container">
        <div class="bg_btn">
            <!-- login session 있을때는 문제조회로 , 없을때는 로그인으로 -->
            {% if user.is_authenticated %}
            <button class="bg_btn_style" onclick="location.href='{%url 'sfoj_system:list' %}'">시작하기</button>
            {% else %}
            <button class="bg_btn_style" onclick="location.href='{%url 'common:login' %}'">시작하기</button>
            {% endif %}
        </div>
    </div>
{% endblock %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>